version: '3.8'

services:
  db:
    image: postgres:14
    container_name: motturental_db
    restart: always
    tty: true
    volumes:
      - ./newpgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=MottuRental
    ports:
      - "5432:5432"

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"  # Porta de acesso à interface de gerenciamento do RabbitMQ
      - "5672:5672"    # Porta de comunicação do RabbitMQ para as mensagens

  mongodb:
    image: mongo:5
    container_name: motturental_mongodb
    restart: always
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: MottuRentalMongoDB

  app:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: motturental_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=MottuRental;Username=postgres;Password=root
      - ConnectionStrings__MongoDbConnection=mongodb://mongodb:27017/MottuRentalMongoDB
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=rabbitmq
      - RabbitMQ__Password=rabbitmq
      - RabbitMQ__VirtualHost=/
    ports:
      - "8080:80"
    depends_on:
      - db
      - rabbitmq
      - mongodb

volumes:
  newpgdata:
  mongo_data: